pom.xml
src/main/java/nl/tudelft/dnainator/App.java
src/test/java/nl/tudelft/dnainator/AppTest.java

The previous configuration was using deprecated syntax. This commit
fixes that and enables more configuration options for the used plugins.
Some options might be too strict (especially fail as soon as possible,
even on the smallest issues) but we will see in due time
how (un)necessary and annoying this will be.
~~TODO: add Cobertura and test if PMD/CPD and FindBugs are actually called. Checkstyle is confirmed to be working.~~

[RDY] Refactor Maven's POM

---

checkstyle.xml
pom.xml

This commit fixes issue #9. Checkstyle config was fixed by @pvanagtmaal.

Update Checkstyle to 6.5.

---

pom.xml

Modules present:
- CheckStyle
- Cobertura
- FindBugs
- JavaDOC
- PMD
- jxr
Use mvn site to generate a project site
Use mvn site:deploy to deploy a project site
Use mvn site-deploy to generate and deploy a project site

[RDY] Automated generating and uploading the maven project site

---

LICENSE

As discussed with the TA: a permissive license, with the copyright
belonging to TU Delft.

[RFC] Add a LICENSE file

---

src/main/java/nl/tudelft/dnainator/DNAinator.java

Use the native menu bar. Only applies when using OS X.

[RDY] Use native menubar when using OS X

---

pom.xml
src/main/java/nl/tudelft/dnainator/graph/DNAGraph.java
src/main/java/nl/tudelft/dnainator/graph/DNALayout.java
src/main/java/nl/tudelft/dnainator/graph/TreeGenerator.java
src/main/java/nl/tudelft/dnainator/ui/DNAViewer.java
src/test/java/nl/tudelft/dnainator/AllTests.java
src/test/java/nl/tudelft/dnainator/graph/DNAGraphTest.java
src/test/java/nl/tudelft/dnainator/graph/DNALayoutTest.java
src/test/java/nl/tudelft/dnainator/graph/TreeGeneratorTest.java

The tree generator uses the index of a node to determine it's depth and relative positioning.
The layout is passed a graph, and for now only does some basic positioning.
This should be extended for a force based layout in the y-direction.

[RFC] Add a tree generator and a layout, mockito and tests.

---

src/main/java/nl/tudelft/dnainator/ui/actions/OpenAction.java

As mentioned during the feedback meeting today. I have also fixed the file filter.

[RFC] Remember directory and fix the file filter.

---

src/main/java/nl/tudelft/dnainator/ui/DNAViewer.java
src/main/java/nl/tudelft/dnainator/ui/Window.java
src/main/java/nl/tudelft/dnainator/ui/actions/OpenAction.java
src/main/java/nl/tudelft/dnainator/util/FileLoader.java

I'm still working on this, but feedback as I go would be nice.

[RDY] Hook up parser into UI

---

src/main/java/nl/tudelft/dnainator/Main.java
src/main/java/nl/tudelft/dnainator/ui/DNAinator.java
src/main/java/nl/tudelft/dnainator/ui/controllers/GraphController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/services/FileLoadService.java
src/main/java/nl/tudelft/dnainator/ui/widgets/ExceptionDialog.java
src/main/resources/ui/fxml/dnainator.fxml
src/main/resources/ui/fxml/viewer.fxml
src/test/java/nl/tudelft/dnainator/ui/services/FileLoadServiceTest.java

This is 1) cleaner and 2) necessary to implement a neo4j singleton that @gfokkema will do next :)

[RFC] Move some code around

---

src/main/java/nl/tudelft/dnainator/graph/Neo4jGraphDatabase.java
src/main/java/nl/tudelft/dnainator/graph/Neo4jSingleton.java
src/main/java/nl/tudelft/dnainator/ui/services/FileLoadService.java
src/test/java/nl/tudelft/dnainator/graph/Neo4jGraphTest.java
src/test/java/nl/tudelft/dnainator/graph/impl/Neo4jSingletonTest.java
src/test/java/nl/tudelft/dnainator/ui/services/FileLoadServiceTest.java

[RDY] Improve the Neo4jSingleton and our ability to test it.

---

src/main/java/nl/tudelft/dnainator/core/DefaultSequenceNode.java
src/main/java/nl/tudelft/dnainator/core/SequenceNode.java
src/main/java/nl/tudelft/dnainator/graph/Graph.java
src/main/java/nl/tudelft/dnainator/graph/Neo4jGraphDatabase.java
src/main/java/nl/tudelft/dnainator/ui/controllers/GraphController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/drawables/DrawableEdge.java
src/main/java/nl/tudelft/dnainator/ui/drawables/DrawableNode.java
src/main/java/nl/tudelft/dnainator/ui/layouts/TopoLayout.java
src/main/java/nl/tudelft/dnainator/ui/models/GraphModel.java
src/main/java/nl/tudelft/dnainator/ui/views/SequenceView.java
src/main/java/nl/tudelft/dnainator/ui/views/View.java
src/main/resources/ui/fxml/dnainator.fxml
src/main/resources/ui/fxml/viewer.fxml
src/main/resources/ui/style.css

This is an early WIP PR to show progress and keep everyone up to date. There is basic drawing but many things are not done:
* Edges are currently not drawn;
* ~~`GraphModel` currently hardcodes a fake dataset. This obviously has to go and it has to interact with `Neo4jGraphDatabase`.~~ **Very**, *very* basic integration is here now. Further integration I had imagined to be a task for @balletie and @gfokkema;
* There is only one `View` at the moment, the `SequenceView`. In due time all defined zoomlevels should have their own view. ~~There is no option at the moment to set the active view, as there is only one;~~
* When we have multiple views, it might be necessary to define additional models. We will see in due time;
* ~~We should create some layout managers …

[RDY] Start drawing graphs.

---

pom.xml
src/main/java/nl/tudelft/dnainator/graph/Neo4jGraphDatabase.java
src/main/java/nl/tudelft/dnainator/graph/Neo4jSingleton.java
src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java
src/main/java/nl/tudelft/dnainator/parser/buffered/JFASTANodeParser.java
src/main/java/nl/tudelft/dnainator/ui/controllers/GraphController.java
src/main/java/nl/tudelft/dnainator/ui/services/FileLoadService.java
src/test/java/nl/tudelft/dnainator/ui/services/FileLoadServiceTest.java

ATTENTION: depends on #41. It must be merged before this.
Removed code redundancies

[RFC] Cleanup code

---

src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/services/FileLoadService.java
src/main/java/nl/tudelft/dnainator/ui/widgets/ProgressDialog.java

ATTENTION: #41 and #48 should be merged first!
Automatically draws the graph when the file has loaded, and closes the database when the request is cancelled.

[RDY] Add Alert while loading a file with a progress indicator

---

src/main/java/nl/tudelft/dnainator/graph/Neo4jGraphDatabase.java
src/main/java/nl/tudelft/dnainator/parser/EdgeParser.java
src/main/java/nl/tudelft/dnainator/parser/NodeParser.java
src/main/java/nl/tudelft/dnainator/parser/buffered/BufferedEdgeParser.java
src/main/java/nl/tudelft/dnainator/parser/buffered/BufferedNodeParser.java
src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java
src/main/java/nl/tudelft/dnainator/parser/buffered/JFASTANodeParser.java
src/main/java/nl/tudelft/dnainator/ui/services/FileLoadService.java

[RDY] Close inputstreams when done parsing

---

src/main/java/nl/tudelft/dnainator/ui/DNAinator.java

[RDY] Add minimum size to the Application window

---

src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/drawables/DrawableEdge.java
src/main/java/nl/tudelft/dnainator/ui/drawables/DrawableNode.java
src/main/java/nl/tudelft/dnainator/ui/views/View.java
src/main/java/nl/tudelft/dnainator/ui/widgets/ExceptionDialog.java
src/main/java/nl/tudelft/dnainator/ui/widgets/contexts/EdgeContext.java
src/main/java/nl/tudelft/dnainator/ui/widgets/contexts/NodeContext.java
src/main/java/nl/tudelft/dnainator/ui/widgets/contexts/ViewContext.java
src/main/java/nl/tudelft/dnainator/ui/widgets/dialogs/AboutDialog.java
src/main/java/nl/tudelft/dnainator/ui/widgets/dialogs/ExceptionDialog.java
src/main/java/nl/tudelft/dnainator/ui/widgets/dialogs/ProgressDialog.java

WIP as I think there might be more coming today or tomorrow.

[RDY] Some in-between quick fixes

---

src/main/java/nl/tudelft/dnainator/ui/DNAinator.java

Some stupid java bug caused the screen to minimise on startup, only on OSX. Bug report is being submitted to Oracle about this. Actually, the fix leads to cleaner code so we don't care too much :)

[RFC] Fix bug on OSX that minimizes screen on startup.

---

src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/drawables/PhylogeneticEdge.java
src/main/java/nl/tudelft/dnainator/ui/drawables/PhylogeneticLabel.java
src/main/java/nl/tudelft/dnainator/ui/drawables/PhylogeneticNode.java
src/main/java/nl/tudelft/dnainator/ui/widgets/PhylogeneticTree.java
src/main/resources/ui/fxml/dnainator.fxml

This PR adds a complete phylogenetic tree implementation. It also changes the main window, in that the DNA view and the phylogenetic tree view are together wrapped in a split pane.

[RFC] Draw phylogenetic tree

---

src/main/java/nl/tudelft/dnainator/ui/controllers/ViewController.java
src/main/resources/ui/fxml/view.fxml

Scrolling using arrow keys. Speed increases while key is pressed, until a max speed is reached.

[RFC] Allow for arrow key scrolling

---

src/main/java/nl/tudelft/dnainator/ui/controllers/ViewController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/views/View.java
src/main/resources/ui/fxml/dnainator.fxml

View and ViewController were slightly rewritten in order for zoom functionality to be implemented nicely.

[RDY] Enable zoom hotkeys (+,-, ctrl/cmd and +, ctrl/cmd and +)

---

src/main/java/nl/tudelft/dnainator/ui/splashscreen/SplashScreen.java

Add icon to the splashscreen (taskbar).
Fixes #90.

[RDY] Add icon for splashscreen

---

src/main/java/nl/tudelft/dnainator/ui/AllColorsInUseException.java
src/main/java/nl/tudelft/dnainator/ui/ColorServer.java
src/main/java/nl/tudelft/dnainator/ui/controllers/FileOpenController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/StrainViewController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/drawables/PhylogeneticEdge.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/AbstractNode.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/Edge.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/InternalNode.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/Label.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/LeafNode.java
src/main/java/nl/tudelft/dnainator/ui/views/PhylogeneticView.java
src/main/java/nl/tudelft/dnainator/ui/views/StrainView.java
src/main/resources/ui/fxml/dnainator.fxml
src/main/resources/ui/fxml/view.fxml
src/main/resources/ui/style.css
src/main/resources/ui/tango.css
src/test/java/nl/tudelft/dnainator/ui/ColorServerTest.java

Basically WIP, since it still needs to be connected to `StrainView`. However, the work implemented here is standalone and works properly so we might want to merge it already and do the connection in a separate PR.

[RDY] Phylogenetic View: highlight leaves and 'collapse' subtrees

---

pom.xml
src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jGraph.java
src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jSingleton.java
src/main/java/nl/tudelft/dnainator/graph/impl/query/ClusterEvaluator.java
src/main/java/nl/tudelft/dnainator/graph/impl/query/NodeQuery.java
src/main/java/nl/tudelft/dnainator/ui/ColorServer.java
src/main/java/nl/tudelft/dnainator/ui/controllers/FileOpenController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/StrainViewController.java
src/main/java/nl/tudelft/dnainator/ui/controllers/WindowController.java
src/main/java/nl/tudelft/dnainator/ui/drawables/DrawableEdge.java

Since fixing javadoc means the site-deploy command works again, maybe this PR can be used to fix all outstanding issues.

[RDY] Fix JavaDoc, PMD and FindBugs warnings, and PMD configuration

---

doc/sources/global.uxf

This reverts commit 0e4aabc2ef4a023c450efab620631af144c31f1d.

[RFC] Revert "Update global UML"

---

src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/AbstractNode.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/CollapsedNode.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/InternalNode.java
src/main/java/nl/tudelft/dnainator/ui/drawables/phylogeny/LeafNode.java
src/main/resources/ui/style.css

[RDY] Implement collapsing functionality on phylogenetic tree.

---

pom.xml

Run with mvn clean compile assembly:single

[RDY] Add binary release for the customer.

---

pom.xml

Neo4j has a new release with full Java 8 compatibility.

[RDY] Bump version of dnainator and some dependencies.

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WindowController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/AbstractView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/StrainView.java
dnainator-javafx/src/main/resources/fxml/dnainator.fxml

Added on hotkeys `<meta>+R` and `<meta>+T.`

[RDY] Add reset zoom and reset position functionality.

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/AbstractViewController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Strain.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Thresholds.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/AbstractView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/StrainView.java
dnainator-javafx/src/test/java/nl/tudelft/dnainator/javafx/drawables/strains/StrainTest.java

Add zoom bounds based on the scaling (zooming).
After #124.

[RDY] Zoom bounds

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WelcomeController.java

Fix the bug to load "invisible" db entries.

[RDY] Add invalidation of empty db paths

---

dnainator-javafx/src/main/resources/fxml/welcome.fxml

When using a button bar, the spacing works regardless of system font.

[RDY] Welcomescreen: use a button bar for proper spacing

---

dnainator-core/src/main/java/nl/tudelft/dnainator/graph/Graph.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jGraph.java
dnainator-javafx/src/test/java/nl/tudelft/dnainator/javafx/drawables/strains/StrainTest.java

Also removed the getRanks function, which returns the whole graph.

[RDY] Add a getMaxRank function, to be used in the minimap later.

---

dnainator-core/src/main/java/nl/tudelft/dnainator/core/EnrichedSequenceNode.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jBatchBuilder.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jGraph.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jSequenceNode.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/NodeLabels.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/PropertyTypes.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/RelTypes.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/command/AnalyzeCommand.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/query/ClusterEvaluator.java
dnainator-core/src/test/java/nl/tudelft/dnainator/graph/impl/Neo4jGraphTest.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/FileOpenController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/services/GraphLoadService.java

From this branch, we can look into a persistent phylogenetic tree.

[RDY] Load the phylogenetic tree into the database.

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/FileOpenController.java
dnainator-javafx/src/main/resources/fxml/openpane.fxml
dnainator-javafx/src/main/resources/fxml/welcome.fxml

Adds some text to the open file pane to make it more user friendly.

[RDY] Add title/subtitle to openpane

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/PropertyPaneController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/DownSlideAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/LeftSlideAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/RightSlideAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/SlidingAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/TransitionAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/UpSlideAnimation.java

[RDY] Animation property pane on click

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/LeftSlideAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/RightSlideAnimation.java

#150 was merged too soon.
Cleanup some lines that still had to be removed.

[RDY] Cleanup animations

---

dnainator-core/src/main/java/nl/tudelft/dnainator/graph/Graph.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jGraph.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/SemanticDrawable.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/Thresholds.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Strain.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/StrainView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/Minimap.java
dnainator-javafx/src/main/resources/style.css

~~CSS still needs to be done properly and~~ I *think* (haven't checked) that the minimap's highlight can go out of view, at least on the right side.
Since I can't, please properly test this on higher-strain samples such as the 100 or 671 strains. ~~The highlight might get too narrow when there are that many ranks.~~
~~Also, we should ask the customer tomorrow if they want it based on the amount of basepairs.~~ ~~EDIT: in the process of converting.~~ Done.

[RDY] Add a minimap

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WindowController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/dialogs/HotkeyHelpDialog.java
dnainator-javafx/src/main/resources/fxml/dnainator.fxml
dnainator-javafx/src/main/resources/style.css

Add a short cut help dialog.
Shows when the user presses F1.

[RDY] Add help dialog

---

dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/Annotation.java
dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/AnnotationCollection.java
dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/DRMutation.java
dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/DRMutationFactory.java
dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/impl/AnnotationCollectionImpl.java
dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/impl/BioJavaAnnotation.java
dnainator-core/src/main/java/nl/tudelft/dnainator/annotation/impl/DRMutation.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jAnnotation.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jBatchBuilder.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jGraph.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/properties/DRMutationProperties.java
dnainator-core/src/main/java/nl/tudelft/dnainator/parser/DRMutationParser.java
dnainator-core/src/main/java/nl/tudelft/dnainator/parser/impl/DRMutationParserImpl.java
dnainator-core/src/test/java/nl/tudelft/dnainator/annotation/DRMutationFactoryTest.java
dnainator-core/src/test/java/nl/tudelft/dnainator/annotation/DRMutationTest.java
dnainator-core/src/test/java/nl/tudelft/dnainator/annotation/impl/AnnotationImpl.java
dnainator-core/src/test/java/nl/tudelft/dnainator/parser/impl/DRMutationParserTest.java
dnainator-core/src/test/resources/annotations/dr_test.txt
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/FileOpenController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/annotations/Gene.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/services/GraphLoadService.java
dnainator-javafx/src/main/resources/fxml/openpane.fxml
dnainator-javafx/src/test/java/nl/tudelft/dnainator/javafx/services/GraphLoadServiceTest.java
dnainator-javafx/src/test/resources/annotations/dr_test.txt

~~Tests need to be added.~~
~~Comes after #158~~

[RDY] Add parser for known mutations and attach it to the GUI. 

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WindowController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/dialogs/HotkeyHelpDialog.java
dnainator-javafx/src/main/resources/fxml/dnainator.fxml

Adds the disability to open more than one hotkey menu.
After #169.

[RDY] Hotkeys disable

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/AbstractViewController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/AbstractView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/StrainControl.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/dialogs/ExceptionDialog.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/dialogs/ProgressDialog.java
dnainator-javafx/src/main/resources/fxml/dnainator.fxml
dnainator-javafx/src/main/resources/fxml/openpane.fxml
dnainator-javafx/src/main/resources/fxml/propertypane.fxml
dnainator-javafx/src/main/resources/fxml/view.fxml
dnainator-javafx/src/main/resources/fxml/welcome.fxml
dnainator-javafx/src/main/resources/style.css

Adds a light colored css theme.

[RDY] Apply new CSS

---

dnainator-javafx/src/main/resources/style.css

Fixes remaining issues in #174.

[RDY] Remove unused CSS, fix edges

---

dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jBatchBuilder.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jGraph.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/Neo4jSequenceNode.java
dnainator-core/src/main/java/nl/tudelft/dnainator/graph/impl/query/AllClustersQuery.java
dnainator-core/src/main/java/nl/tudelft/dnainator/parser/TreeParser.java
dnainator-core/src/main/java/nl/tudelft/dnainator/parser/impl/NodeIterator.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/AbstractViewController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/PropertyPaneController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WelcomeController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WindowController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/phylogeny/CollapsedNode.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/phylogeny/InternalNode.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/phylogeny/LeafNode.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/ClusterDrawable.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Edge.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Pie.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Strain.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/Thresholds.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/services/DirectoryLoadService.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/services/GraphLoadTask.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/AbstractView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/PhylogeneticView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/Minimap.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/TransitionAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/dialogs/AboutDialog.java
dnainator-javafx/src/main/resources/fxml/welcome.fxml

Cleaned up the code, removed redundant lines/statements/declarations/lambdas/variables 
Comes after #183

[RDY] Code cleanup

---

dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/ColorMap.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/AbstractViewController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/OpenPaneController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/controllers/WelcomeController.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/phylogeny/InternalNode.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/drawables/strains/ClusterDrawable.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/services/DirectoryListingService.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/views/StrainView.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/JumpTo.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/animations/TransitionAnimation.java
dnainator-javafx/src/main/java/nl/tudelft/dnainator/javafx/widgets/dialogs/ExceptionDialog.java

Supersedes #188, which I did not feel like rebasing. This one is a cherry-pick of the commit on top of #187

[RDY] Add comments to frontend code
